### ISSUE TITLE
cannot run colab directly

### ISSUE THREAD

**Issue by FingerRec** [LAION-AI/dalle2-laion#10]
Hi,

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/numpy/lib/shape_base.py](https://w20pl110o4-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20220714-060045-RC00_460927563#) in split(ary, indices_or_sections, axis)
    866     try:
--> 867         len(indices_or_sections)
    868     except TypeError:

TypeError: object of type 'int' has no len()

When I run this jupyter notebook in colab, the last part (rerank) except the above exceptions.

**Comment by nousr** [comment]
As models are increasing in VRAM usage, I believe we are moving away from google colab support. This, combined with recent overhauls this is likely an outdated issue. 

If you run into any new problems do not hesitate to open a new issue with details :)
