### ISSUE TITLE
Notebook still using dalle2_pytorch==0.15

### ISSUE THREAD

**Issue by cdusold** [LAION-AI/dalle2-laion#13]
An update to the notebook would be nice, since the version it installs does not have inpainting code yet. The checkpoints aren't directly compatible, so I'm guessing this will take a while.

They're almost compatible. `*.gamma` values are changed to `*.g`, and the noise_scheduler variables are now children of the module noise_scheduler instead of at the top level of 'model'. There are other things that are preventing loading the older checkpoints, though, and this is a big reason the major version number increased. If you skip optimizer loading and some of the other things you may be able to update the inference model at least.

After updating everything I could find, I found that "noise_scheduler.p2_loss_weight", and "net.null_text_embed" are missing. I'm going to play around with it for a bit and see if I can get it loading right.

**Comment by Veldrovive** [comment]
I'll be removing the old notebook in a bit and replacing it with the new InferenceScript method for evaluation because it is too difficult to load the models without those helper methods now.

**Comment by nousr** [comment]
@cdusold thanks for taking the time to explore this!

It looks like the move to Veldrovive's inference scripts has begun, though. As a result, this issue is likely outdated in favor of the new method. 

If you have further questions regarding supported inference methods don't hesitate to reach out!
