### ISSUE TITLE
All Models Out of Date(Possible downgrade feature?)

### ISSUE THREAD

**Issue by JustAHippo** [LAION-AI/dalle2-laion#18]
All the current models get downloaded for 1.1.0, but the latest version is 1.4.6. It would be great to have an option to downgrade the version of DALLE2-pytorch so these are compatible for the current moment!

**Comment by Veldrovive** [comment]
`DALLE2-pytorch` should be manually downgraded with `pip install DALLE2-pytorch==1.1.0` since messing with library versions inside another library is a recipe for disaster. What I can add is a message for how to change to the correct version inside that version mismatch message.

**Comment by Veldrovive** [comment]
The command for switching to the correct dalle2-pytorch version is now printed out after the warning message. a13198cc8b0c5ad4d340af675365c06bed1b8355

**Comment by rom1504** [comment]
Why can't we put ==1.1.0 in setup.py ?
