### ISSUE TITLE
Performance compared to dalle-mini

### ISSUE THREAD

**Issue by kargarisaac** [LAION-AI/dalle2-laion#22]
Hello,

I'm trying to compare the performance of dalle2 (this repo - colab) with dalle-mini (https://huggingface.co/spaces/dalle-mini/dalle-mini). The dalle-mini performs much better. I cannot get meaningful images from dalle2. Is there an specific setting I have to do to get a good result? Or it is not completely trained? Or sth else?

for example: "a programmer sitting in a coffeeshop."

dalle2 output:
![image](https://user-images.githubusercontent.com/24753756/183218812-b9a35378-5837-40d3-a00c-1d5010babb09.png)

dalle-mini output:
![dallemini_2022-8-6_0-9-16](https://user-images.githubusercontent.com/24753756/183217887-887742e0-7f28-465b-93e3-dc77fb6967fd.png)

**Comment by nousr** [comment]
> Is there an specific setting I have to do to get a good result? Or it is not completely trained? Or sth else?

We are still working towards a fully trained model--tools and supporting code are being worked on to slingshot our dalle2 recreation into a much more usable state, everything right now is still very early on in development (relatively speaking) compared to dalle-mini!

Stay tuned :D
