### ISSUE TITLE
Want to make a contribution ...

### ISSUE THREAD

**Issue by RaSah673** [LAION-AI/dalle2-laion#23]
Hey guys, I want to make a contribution ... to this dalle2-laion, but don't know where to start from. Do you have any tutorial or documentation?

**Comment by Veldrovive** [comment]
Hey, I've been writing the new inference scripts. I'll get documentation in asap, but if you have something in particular you are interested in I can prioritize getting relevant information more available.

**Comment by Veldrovive** [comment]
You can now find basic documentation for the inference script [here](https://github.com/LAION-AI/dalle2-laion/tree/main/dalle2_laion).
