### ISSUE TITLE
support ddim sampling?

### ISSUE THREAD

**Issue by heurainbow** [LAION-AI/dalle2-laion#26]
This diffusion model requires 1000 steps for decoding and Unet. 
https://github.com/lucidrains/DALLE2-pytorch/commit/b7e22f7da0bb4ec2b38eddae7f481dd917718591 proposed a commit of ddim to use fewer steps. Any integration in this repo?

**Comment by nousr** [comment]
this should be supported now iirc, feel free to re-open if it is not!
