### ISSUE TITLE
Error has occurred in google colab notebook

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [LAION-AI/dalle2-laion#29]
Hello,

Thanks for your valuable work!
When I run notebook of dalle2-laion on google colab, the following error occurred.

```
AttributeError                            Traceback (most recent call last)
[<ipython-input-16-578a5f9162bc>](https://localhost:8080/#) in <module>
     86     img.save(f"./reranked_output/example_{index}.png")
     87 
---> 88 rerank_test(5, 50)

5 frames
[/usr/local/lib/python3.7/dist-packages/ftfy/__init__.py](https://localhost:8080/#) in fix_text(text, config, **kwargs)
    302     pos = 0
    303     while pos < len(text):
--> 304         textbreak = text.find("\n", pos) + 1
    305         if textbreak == 0:
    306             textbreak = len(text)

AttributeError: 'list' object has no attribute 'find'
```

If you has any idea, please let me know that.

Thank you.

**Comment by shanmukhaVoggu** [comment]
I am facing the same issue, There are some fixes here : [https://stackoverflow.com/questions/23201351/list-object-has-no-attribute-find](https://stackoverflow.com/questions/23201351/list-object-has-no-attribute-find)

But not sure editing the '/usr/local/lib/python3.7/dist-packages/ftfy/__init__.py' file resolves the error in google colab

**Comment by nousr** [comment]
the colab notebook has been removed from the readme as it is outdated. please use the inference pipeline locally on a machine with enough VRAM 👍

**Comment by Ishihara-Masabumi** [comment]
Thanks.
