### ISSUE TITLE
about pre-trained models

### ISSUE THREAD

**Issue by zhangchen234** [LAION-AI/dalle2-laion#32]
Thanks for your work. I have a question about pre-trained models（https://huggingface.co/laion/DALLE2-PyTorch/tree/main）. Is there a description about the pre-training models or which pre-training model is the best?

**Comment by nousr** [comment]
there is no clear "best" model, the checkpoints there were simply a public sandbox that we would save to in the spirit of open-source development 😄 

at this point all checkpoints listed there are far out of date with the main repository and would require manual effort to run inference on
