### ISSUE TITLE
gradio_inference: DuplicateBlockError

### ISSUE THREAD

**Issue by divastar** [LAION-AI/dalle2-laion#33]
Hi. Thank you for sharing.
I got this error while trying to run the inference:
   raise DuplicateBlockError(
gradio.exceptions.DuplicateBlockError: At least one block in this Blocks has already been rendered.

Could you advise about that?
Than you

**Comment by nousr** [comment]
the colab notebook is outdated, please use the inference pipeline instead

**Comment by aivyon** [comment]
Hi. Thank you for your response.
I tried to run the python example_inference.py dream
but it would always give me a warning WARNING: This decoder was trained on version 1.1.0 but the current version is 1.11.1. This may result in the model failing to load.  
and will produce garbage results:
![image](https://user-images.githubusercontent.com/50579056/200861707-0fdde516-2be9-4690-bb44-40016f5d284b.png)
 (I definitely installed version 1.1.0 and not 1.11.1)
Is there a way around this?
Thank you
